name: CI

on:
  push:
    branches:
      - latest

# TODO: support tags

jobs:
  qa:
    name: Quality assurance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: docker build -t pouchdb-adapter-react-native-leveldb .

      - name: Unit test
        run: docker run --rm pouchdb-adapter-react-native-leveldb test

  publish:
    name: Publish
    needs: [qa]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
