name: CI

on:
  push:
    paths-ignore:
      - LICENSE
      - '**.md'

jobs:
  qa:
    name: Quality assurance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: docker build -t pouchdb-adapter-react-native-leveldb .

      - name: Test
        run: docker run --rm pouchdb-adapter-react-native-leveldb test
