name: CI

on:
  push:
    paths:
      - '**.js'
      - '**.json'
      - '**.yaml'
      - Dockerfile

jobs:
  qa:
    name: Quality assurance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: docker build -t pouchdb-adapter-react-native-leveldb .

      - name: Unit test
        run: docker run --rm -t pouchdb-adapter-react-native-leveldb test
